---
abstract: 'C implementation of the ISAAC PRNG Algorithm'
author:
  - 'Jonathan Yu <frequency@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 0
  Test::NoWarnings: 0.084
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3607'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Random-ISAAC-XS
provides:
  Math::Random::ISAAC::XS:
    file: lib/Math/Random/ISAAC/XS.pm
    version: 1.002
recommends:
  Math::Random::ISAAC: 0
requires:
  Test::More: 0.62
  perl: 5.006
resources:
  Ratings: http://cpanratings.perl.org/d/Math-Random-ISAAC-XS
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Math-Random-ISAAC-XS
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Math-Random-ISAAC-XS
version: 1.002
