---
name: Math-Random-ISAAC-XS
version: 1.001
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: C implementation of the ISAAC PRNG Algorithm
license: unrestricted
requires:
  Test::More: 0.62
  perl: 5.006
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 0
  Test::NoWarnings: 0.084
recommends:
  Math::Random::ISAAC: 0
dynamic_config: 1
provides:
  Math::Random::ISAAC::XS:
    file: lib/Math/Random/ISAAC/XS.pm
    version: 1.001
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  Ratings: http://cpanratings.perl.org/d/Math-Random-ISAAC-XS
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Math-Random-ISAAC-XS
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Math-Random-ISAAC-XS
