---
abstract: 'C implementation of the ISAAC PRNG algorithm'
author:
  - 'Jonathan Yu <jawnsy@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 0
  Module::Build: 0.3601
  Test::NoWarnings: 0.084
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Random-ISAAC-XS
requires:
  Math::Random::ISAAC: 0
  Test::More: 0.62
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Math-Random-ISAAC-XS
  homepage: http://search.cpan.org/dist/Math-Random-ISAAC-XS
  repository: git://github.com/jawnsy/Math-Random-ISAAC-XS.git
version: 1.003
